repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: ['-i']
        files: \.(cpp|h)$
        exclude: ^\.pio/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.pio/
      - id: end-of-file-fixer
        exclude: ^\.pio/
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: ^\.pio/
